language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7
sudo: false
dist: xenial
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.5
      env: GROUP=docs
cache:
  pip: true
  directories:
    - ~/.npm  # NPM cache
before_install:
  - pip install -U pip setuptools
  - nvm install 8
install:
  - pip install --upgrade -e ".[test, examples, docs]"
script:
  - |
    if [[ $GROUP == python ]]; then
      py.test -l --nbval-lax --current-env examples;
    elif [[ $GROUP == docs ]]; then
      EXIT_STATUS=0
      cd docs
      make html || EXIT_STATUS=$?
      make linkcheck || EXIT_STATUS=$?
      cd ..
      python -m pytest_check_links || EXIT_STATUS=$? ;
      (exit $EXIT_STATUS)
    fi
